services:
  backend:
    build: ./backend
    ports:
      - "5175:5175"
      - "7011:7011"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
